//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// iRecHS2s.rc で使用
//
#define IDC_MYICON                      2
#define IDD_IRECHS2S_DIALOG             102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_IRECHS2S                    107
#define IDI_SMALL                       108
#define IDC_IRECHS2S                    109
#define IDR_MAINFRAME                   128
#define IDD_CAMERA_LIST                 129
#define IDD_DIALOG1                     130
#define IDD_CAM_REGION                  130
#define IDD_DIALOG_CameraParameter      131
#define IDD_OPTIONS                     132
#define IDD_OBJECTMAP                   134
#define IDD_DIALOG_CALIBRESULT          135
#define IDD_DAC                         136
#define IDC_LIST1                       1000
#define IDC_CAMERA_LIST                 1000
#define IDC_EDIT_OFFSETX                1001
#define IDC_EDIT_OFFSETY                1002
#define IDC_EDIT_WIDTH                  1003
#define IDC_EDIT_HEIGHT                 1004
#define IDC_SPIN_OFFSETX                1005
#define IDC_SPIN_OFFSETY                1006
#define IDC_SPIN_WIDTH                  1007
#define IDC_SPIN_HEIGHT                 1008
#define IDC_CAM_BITMAP                  1009
#define IDC_CHECK_ExposureCompensationAuto 1010
#define IDC_SLIDER_ExposureCompensation 1011
#define IDC_CHECK_FrameRateAuto         1012
#define IDC_SLIDER_FrameRate            1013
#define IDC_STATIC_FrameRate            1014
#define IDC_STATIC_ExposureTime         1015
#define IDC_EDIT_FrameRate              1016
#define IDC_CHECK_ExposureTimeAuto      1017
#define IDC_SLIDER_ExposureTime         1018
#define IDC_CHECK_GainAuto              1019
#define IDC_STATIC_Gain                 1020
#define IDC_SLIDER_Gain                 1021
#define IDC_EDIT_ExposureCompensation   1022
#define IDC_STATIC_BlackLevel           1023
#define IDC_SLIDER_BlackLevel           1024
#define IDC_EDIT_ExposureTime           1025
#define IDC_EDIT_Gain                   1026
#define IDC_EDIT_BlackLevel             1027
#define IDC_CAMPARAM_BITMAP             1028
#define IDC_UseTopFitting               1029
#define IDC_UseBottomFitting            1030
#define IDC_UseGleaning                 1031
#define IDC_SLIDER_THRESHOLD            1032
#define IDC_SLIDER_REFTHRESHOLD         1033
#define IDC_SLIDER_P_ANGLE              1034
#define IDC_SLIDER_P_LENGTH             1035
#define IDC_SLIDER_SE_LENGTH            1036
#define IDC_STATIC_THRESHOLD            1037
#define IDC_STATIC_REFTHRESHOLD         1038
#define IDC_STATIC_P_ANGLE              1039
#define IDC_STATIC_P_LENGTH             1040
#define IDC_STATIC_SE_LENGTH            1041
#define IDC_SLIDER_Median_NUM           1042
#define IDC_SLIDER_MA_NUM               1043
#define IDC_SLIDER_PASSIVE_SD           1044
#define IDC_SLIDER_FIXATION_PIXEL       1045
#define IDC_RADIO_NONE                  1046
#define IDC_RADIO_Median                1047
#define IDC_RADIO_MVA                   1048
#define IDC_COMBO_METHOD                1049
#define IDC_EDIT1                       1050
#define IDC_SLIDER_FIXATION_ANGLE       1050
#define IDC_EDIT2                       1051
#define IDC_SLIDER_FIXATION_DURATION    1051
#define IDC_EDIT3                       1052
#define IDC_SLIDER_BLINK                1052
#define IDC_EDIT4                       1053
#define IDC_UseMovingROI                1053
#define IDC_EDIT5                       1054
#define IDC_STATIC_BLINK                1054
#define IDC_EDIT6                       1055
#define IDC_UsePreviousImage            1055
#define IDC_EDIT7                       1056
#define IDC_EDIT8                       1057
#define IDC_EDIT9                       1058
#define IDC_EDIT10                      1059
#define IDC_EDIT11                      1060
#define IDC_EDIT12                      1061
#define IDC_EDIT13                      1062
#define IDC_EDIT14                      1063
#define IDC_EDIT15                      1064
#define IDC_EDIT16                      1065
#define IDC_EDIT17                      1066
#define IDC_EDIT18                      1067
#define IDC_EDIT19                      1068
#define IDC_EDIT20                      1069
#define IDC_EDIT21                      1070
#define IDC_EDIT22                      1071
#define IDC_EDIT23                      1072
#define IDC_EDIT24                      1073
#define IDC_EDIT25                      1074
#define IDC_EDIT26                      1075
#define IDC_EDIT27                      1076
#define IDC_EDIT28                      1077
#define IDC_EDIT29                      1078
#define IDC_EDIT30                      1079
#define IDC_EDIT31                      1080
#define IDC_EDIT32                      1081
#define IDC_EDIT33                      1082
#define IDC_EDIT34                      1083
#define IDC_EDIT35                      1084
#define IDC_EDIT36                      1085
#define IDC_EDIT37                      1086
#define IDC_EDIT38                      1087
#define IDC_EDIT39                      1088
#define IDC_EDIT40                      1089
#define IDC_EDIT41                      1090
#define IDC_EDIT42                      1091
#define IDC_EDIT43                      1092
#define IDC_EDIT44                      1093
#define IDC_EDIT45                      1094
#define IDC_RADIO_POSITION              1095
#define IDC_RADIO_ANGLE                 1096
#define IDC_CHECK_SAVE                  1097
#define IDC_CHECK_SAVEDEV               1098
#define IDC_STATIC_FIXATION_PIXEL       1099
#define IDC_STATIC_FIXATION_ANGLE       1100
#define IDC_STATIC_FIXATION_DURATION    1101
#define IDC_STATIC_PASSIVE_SD           1102
#define IDC_CALIB_BITMAP                1103
#define IDC_EDIT_INFO                   1104
#define IDC_EDIT_STORED                 1105
#define IDC_COMBO_GAZE_POSITION         1106
#define IDC_CHECK_FLIPH                 1107
#define IDC_CHECK_FLIPV                 1108
#define IDC_COMBO_FAILURE               1117
#define IDC_SLIDER_PUPIL                1120
#define IDC_CHECK_VOLTAGE_LIMIT         1121
#define IDC_TEXT_PUPIL_AMP              1124
#define IDC_TEXT_INFO                   1125
#define IDC_COMBO_DAC_CARD              1126
#define IDC_SLIDER_PIXEL_H              1127
#define IDC_SLIDER_PIXEL_AMP            1128
#define IDC_SLIDER_PIXEL_V              1129
#define IDC_TEXT_PIXEL                  1133
#define IDC_TEXT_PIXEL_AMP              1134
#define IDC_SLIDER_PUPIL_AMP            1135
#define IDC_SLIDER_OBJANG_AMP           1136
#define IDC_SLIDER_OBJANG_V             1137
#define IDC_TEXT_OBJANG                 1138
#define IDC_TEXT_OBJANG_AMP             1139
#define IDC_SLIDER_CAMANG_H             1140
#define IDC_SLIDER_CAMANG_AMP           1141
#define IDC_SLIDER_CAMANG_V             1142
#define IDC_TEXT_CAMANG                 1143
#define IDC_TEXT_CAMANG_AMP             1144
#define IDC_SLIDER_OBJANG_H             1145
#define IDC_TEXT_PUPIL                  1146
#define ID_VIEW_CAMERAVIEW              32771
#define ID_CAMERAVIEW_ROI               32772
#define ID_CAMERAVIEW_PupilOutline      32773
#define ID_PUPIL_OUTLINE                32774
#define ID_PUPIL_CENTER                 32775
#define ID_PUPIL_AREA                   32776
#define ID_PUPIL_EDGE                   32777
#define ID_CAMERAVIEW_CORNEALREFLECTION 32778
#define ID_CAMERAVIEW_REGIONOFINTEREST  32779
#define ID_CAMERAVIEW_INFORMATION       32780
#define ID_CORNEALREFLECTION            32781
#define ID_REGIONOFINTEREST             32782
#define ID_CAMERAVIEW_UNDERTHRESHOLD    32783
#define ID_PUPIL_MINORAXIS              32784
#define ID_VIEW_MIRRORIMAGE             32785
#define ID_DIALOG_INPUTREGION           32786
#define ID_DIALOG_CAMERACONTROL         32787
#define ID_COMMAND_RESETCALIBRATION     32788
#define ID_METHOD_HEADFREE              32789
#define ID_METHOD_HEADFIXED             32790
#define ID_HEADFIXED_PUPILCENTER        32791
#define ID_HEADFIXED_CORNEALREFLECTION  32792
#define ID_OUTPUT_AUTO                  32793
#define ID_OUTPUT_PUPILCENTER           32794
#define ID_OUTPUT_CAMERACOORDINATES     32795
#define ID_OUTPUT_OBJECTCOORDINATES     32796
#define ID_NOISEREDUCTION_NONE          32797
#define ID_NOISEREDUCTION_MOVINGAVERAGE 32798
#define ID_NOISEREDUCTION_MEDIAN        32799
#define ID_DIALOG_OPTIONS               32800
#define ID_DIALOG_OBJECTMAP             32801
#define ID_FILE_PAUSE                   32802
#define ID_ACCELERATOR_ESC              32804
#define ID_ACCELERATOR_SPACE            32805
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32808
#define _APS_NEXT_CONTROL_VALUE         1135
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
